spring:
  datasource:
    url: jdbc:mysql://101.200.85.171:3306/platform?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: sanyuan027
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    # 地址
    host: 101.200.85.171
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 连接超时时间
    timeout: 10s
    # 是否开启ssl
    ssl: false